/**
 * Catálogo de frases do modelo `manut-visita-testes`.
 *
 * Primeiro da Onda 2 (Manutenção). Três cenários — visita paga, visita isenta
 * autorizada pelo gestor, e cliente que dispensou o suporte remoto — cada um
 * com corpo da O.S e indicação técnica próprios.
 *
 * Sem trechos protegidos: este modelo não reescreve o texto com regex.
 *
 * Nomes:
 *   {solicitanteExibido} quem ligou, já com o cargo quando é PJ
 *   {pessoa}   primeiro nome de quem conduz o diálogo
 *   {local}    EMPRESA ou RESIDENCIA, conforme PF/PJ
 *   {canal} {contato} {sinalONU} {oscila} {repetidor}
 *   {disp1} {disp2} {disp3}  dispositivos conectados / Wi-Fi / cabo
 *   {gestor}   quem autorizou a isenção
 *   {dataVisita} {horaVisita} {formaPag}
 *   {clienteCompleto} {protocolo} {bairro} {tecnico} {custoAgenda}
 */
import type { Catalogo } from './tipos';

export const MANUT_VISITA_TESTES: Catalogo = {
  osDispensouRemoto: {
    rotulo: 'O.S — cliente dispensou o suporte remoto',
    texto:
      '{solicitanteExibido} ENTROU EM CONTATO VIA {canal} ({contato}) E SOLICITOU VISITA TECNICA. QUESTIONADO, {pessoa} DISSE QUE "INTERNET ESTA RUIM E DISPENSOU O SUPORTE REMOTO PARA QUAISQUER PROCEDIMENTOS". INFORMEI QUE VISITA POSSUI O CUSTO DE R$50,00 REFERENTE AO DESLOCAMENTO TECNICO, QUE ESTE PODERA SER PAGO EM DINHEIRO, CARTAO OU PIX E QUE PODERA SER ACRESCIDO O CUSTO DE EQUIPAMENTOS DANIFICADOS SE HOUVER. SE DE FATO TIVER PROBLEMAS NA CONEXAO DE INTERNET DE RESPONSABILIDADE DO PROVEDOR VISITA E ISENTA DE CUSTOS. {pessoa} CONCORDOU E CASO HAJA COBRANCA PAGARA NO ATO COM {formaPag}. VISITA AGENDADA PARA {dataVisita} AS {horaVisita} HRS.',
    obrigatorios: ['pessoa', 'dataVisita', 'horaVisita'],
  },
  indicacaoDispensouRemoto: {
    rotulo: 'Indicação técnica — dispensou o remoto',
    texto:
      'TECNICO: PEDIR PARA {pessoa} APRESENTAR PROBLEMA DE TESTE DE INTERNET QUE ELE DIZ TER. COMPARAR MESMO TESTE COM NOTEBOOK E CELULAR DO KIT TECNICO FOTOGRAFAR/FILMAR. SE HOUVER PROBLEMA NOS EQUIPAMENTOS DA EMPRESA (ROTEADOR OU ONU) QUE NAO SEJAM OCASIONADOS, REPARAR OU TROCAR. SE HOUVER PROBLEMAS NESTE QUE FOREM OCASIONADOS, APRESENTAR AO CLIENTE E INFORMAR CUSTOS. CONFERIR INSTALACAO E LIGACOES ELETRICAS, INSTRUIR SOBRE COBERTURA WI-FI (SE NECESSARIO). CASO NAO HAJA PROBLEMAS E VISITA TER SIDO SOMENTE INSTRUTIVA, COBRAR VALOR DA VISITA E SOLICITAR REALIZACAO DO FEEDBACK. TEMPO ESTIMADO: 40 MINUTOS.',
    obrigatorios: ['pessoa'],
  },

  osIsento: {
    rotulo: 'O.S — visita isenta autorizada pelo gestor',
    texto:
      '{solicitanteExibido} ENTROU EM CONTATO VIA {canal} ({contato}) E DISSE QUE ESTA COM LENTIDAO NA CONEXAO COM A INTERNET, QUESTIONADO INFORMOU QUE "TODOS OS DISPOSITIVOS DA {local} FICAM COM A INTERNET LENTA REPETIDAS VEZES AO LONGO DO DIA E NAO CONSEGUE AFERIR A VELOCIDADE DO PLANO EM NENHUM DE SEUS DISPOSITIVOS". REMOTAMENTE VERIFIQUEI QUE USUARIO ESTA CONECTADO, SINAL ONU ({sinalONU} {oscila}) NAO CONSTAM DESCONEXOES, NO MOMENTO HA {disp1} DISPOSITIVOS CONECTADOS AO ROTEADOR, {disp2} VIA WI-FI E {disp3} POR CABO. REPETIDOR: {repetidor}. {pessoa} SOLICITOU VISITA TECNICA PARA VERIFICAR PROBLEMA QUE "DIZ TER". {gestor} AUTORIZOU VISITA ISENTA DE CUSTOS DESDE QUE OS EQUIPAMENTOS ESTEJAM EM PERFEITO ESTADO DE CONSERVACAO. {pessoa} DISSE ESTAR CIENTE E CONCORDOU COM A VISITA QUE FOI AGENDADA PARA {dataVisita} AS {horaVisita} HRS.',
    obrigatorios: ['pessoa', 'dataVisita', 'horaVisita'],
  },
  indicacaoIsento: {
    rotulo: 'Indicação técnica — visita isenta',
    texto:
      'TECNICO: PEDIR PARA QUE {pessoa} APRESENTE OS “PROBLEMAS DE INTERNET” QUE DIZ TER. COMPARAR TESTES ENTRE DISPOSITIVOS DELES COM DISPOSITIVOS (CELULAR E NOTEBOOK) DO KIT TECNICO. VISITA ISENTA DE CUSTOS (CORTESIA). CASO APRESENTAR ALGUM PROBLEMA ATUALIZAR O ROTEADOR COM UMA NOVA FIRMWARE E TESTAR NOVAMENTE, E SE AINDA NAO RESOLVER SUBSTITUIR O ROTEADOR POR UM NOVO. EXPLICAR E TIRAR TODAS AS DUVIDAS DO CLIENTE. TEMPO ESTIMADO 60 MINUTOS.',
    obrigatorios: ['pessoa'],
  },

  osPadrao: {
    rotulo: 'O.S — visita com possível cobrança',
    texto:
      '{solicitanteExibido} ENTROU EM CONTATO VIA {canal} ({contato}) E DISSE QUE ESTA COM LENTIDAO NA CONEXAO COM A INTERNET, QUESTIONADO INFORMOU QUE "TODOS OS DISPOSITIVOS DA {local} FICAM COM A INTERNET LENTA REPETIDAS VEZES AO LONGO DO DIA E NAO CONSEGUE AFERIR A VELOCIDADE DO PLANO EM NENHUM DE SEUS DISPOSITIVOS". REMOTAMENTE VERIFIQUEI QUE USUARIO ESTA CONECTADO, SINAL ONU ({sinalONU} {oscila}) NAO CONSTAM DESCONEXOES, NO MOMENTO HA {disp1} DISPOSITIVOS CONECTADOS AO ROTEADOR, {disp2} VIA WI-FI E {disp3} POR CABO. REPETIDOR: {repetidor}. {pessoa} SOLICITOU VISITA TECNICA PARA VERIFICAR PROBLEMA QUE "DIZ TER". INFORMEI QUE HAVENDO PROBLEMA DE RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTO, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO) OU SOMENTE PARA INSTRUCAO DE USO COBRAMOS VISITA TECNICA DE R$50,00 E ATE MESMO EQUIPAMENTOS DANIFICADOS. {pessoa} DISSE ESTAR CIENTE E CONCORDOU COM A VISITA E CASO HAJA COBRANCA SOLICITOU PAGAR NO ATO COM {formaPag}. VISITA AGENDADA PARA {dataVisita} AS {horaVisita} HRS.',
    obrigatorios: ['pessoa', 'dataVisita', 'horaVisita'],
  },
  indicacaoPadrao: {
    rotulo: 'Indicação técnica — visita com possível cobrança',
    texto:
      'TECNICO: PEDIR PARA QUE {pessoa} APRESENTE OS “PROBLEMAS DE INTERNET” QUE DIZ TER. COMPARAR TESTES ENTRE DISPOSITIVOS DELES COM DISPOSITIVOS (CELULAR E NOTEBOOK) DO KIT TECNICO. CASO NAO TIVER OU APRESENTAR NENHUM PROBLEMA COBRAR VALOR MINIMO DA VISITA DE R$50,00, CASO APRESENTAR ALGUM PROBLEMA ATUALIZAR O ROTEADOR COM UMA NOVA FIRMWARE E TESTAR NOVAMENTE, E SE AINDA NAO RESOLVER SUBSTITUIR O ROTEADOR POR UM NOVO. EXPLICAR E TIRAR TODAS AS DUVIDAS DO CLIENTE. TEMPO ESTIMADO 60 MINUTOS.',
    obrigatorios: ['pessoa'],
  },

  agenda: {
    rotulo: 'Linha da agenda',
    texto: 'MAN TESTES {clienteCompleto} PROT:{protocolo} {custoAgenda} ({tecnico}) - {bairro}',
    obrigatorios: ['clienteCompleto', 'protocolo'],
  },
};
