/**
 * Catálogo de frases do modelo `wifi-extend-ponto`.
 * Compra de 01 roteador adicional para expandir a rede Wi-Fi.
 *
 * ⚠️ VAZAMENTO DE BRANDING: `indicacaoTroca` manda padronizar o nome da rede
 * como "NOME DO CLIENTE_WBR".
 */
import type { Catalogo } from './tipos';

export const WIFI_EXTEND_PONTO: Catalogo = {
  corpoOs: {
    rotulo: 'Corpo da O.S — compra do ponto adicional',
    texto:
      'POR {canal} ({contato}) {quem} SOLICITOU A COMPRA DE 01 ROTEADOR ADICIONAL PARA EXPANDIR A ABRANGÊNCIA DA REDE WI-FI DENTRO DA MESMA {local} EM QUE FOI INSTALADO O PONTO PRINCIPAL {ponto}. VALOR ACORDADO DO ROTEADOR R$360,00 QUE SERÁ PAGO EM {parcela} {pagFrase}. E INSTALAÇÃO/CONFIGURAÇÃO GRÁTIS. VISITA AGENDADA PARA INSTALAÇÃO DO EQUIPAMENTO EM {dataVisita} ÀS {horaVisita} HORAS.',
    obrigatorios: ['dataVisita'],
  },
  indicacaoPadrao: {
    rotulo: 'Indicação técnica — sem troca do roteador primário',
    texto:
      'TÉCNICO: INSTALAR ROTEADOR (MODELO COMPATIVEL AO PLANO) EM LOCAL DE CONCORDANCIA DO CLIENTE E NA MELHOR ÁREA DE COBERTURA WI-FI. CONFIGURAR REDE, CONECTAR TODOS DISPOSITIVOS QUE APRESENTAREM, REALIZAR TESTES DA FUNCIONALIDADE DA INTERNET, AFERIR PLANO COM DISPOSITIVOS DO CLIENTE E OUTROS QUE ESTIVEREM NO LOCAL, FOTOGRAFAR, FILMAR, COMPARAR E EXPLICAR. CORRIGIR QUALQUER INCONSISTÊNCIAS NA INSTALAÇÃO QUE NÃO ESTIVER NO PADRÃO. RECEBER O VALOR DO EQUIPAMENTO E SERVIÇO NA FORMA COMBINADA. TEMPO ESTIMADO 60 MIN.',
    obrigatorios: [],
  },
  indicacaoTroca: {
    // ⚠️ Cita o provedor no padrão de nome de rede.
    rotulo: 'Indicação técnica — com troca do roteador primário',
    texto:
      'TÉCNICO: CONFERIR INSTALAÇÃO E EQUIPAMENTOS EM COMODATO, NÃO HAVENDO DANOS SUBSTITUIR ROTEADOR {roteador} POR ROTEADOR ZTE H-199A E CONFIGURAR COMO PONTO PRINCIPAL. INSTALAR ROTEADOR EXTEND ZTE H-199A OU H-196A EM LOCAL DE CONCORDANCIA DO CLIENTE E NA MELHOR ÁREA DE COBERTURA WI-FI. PADRONIZAR NOME DAS REDES ("NOME DO CLIENTE_WBR"), CONFERIR NAVEGAÇÃO IPv6, PADRONIZAR PORTA E SENHA DE ACESSO REMOTO, LIBERAR ACESSO EXTERNO PELA WAN; TESTAR ABRANGÊNCIA DA REDE WI-FI E EXPLICAR SOBRE COBERTURA, CONECTAR TODOS DISPOSITIVOS QUE APRESENTAR E REALIZAR TESTES, VERIFICAR E EXPLICAR SOBRE EQUIPAMENTOS QUE FUNCIONARAM MELHOR LIGADOS DIRETAMENTE AO ROTEADOR POR CABOS. BAIXAR E INSTALAR OS APP S QUE FAZEM PARTE DO PLANO ESCOLHIDO, TANTO NOS TELEFONES E TV S QUE POSSUÍREM COMPATIBILIDADE PARA FUNCIONAMENTO E NÃO HAVENDO DAR EXPLICAÇÕES. RECEBER O VALOR DO EQUIPAMENTO E SERVIÇO NA FORMA COMBINADA. TEMPO ESTIMADO 60 MIN.',
    obrigatorios: [],
  },
  agenda: {
    rotulo: 'Linha da agenda',
    texto: 'PONTO ADICIONAL {clienteCompleto} PROT:{protocolo} {formaPag} ({tecnico}) - {bairro}',
    obrigatorios: ['clienteCompleto'],
  },
};
