/**
 * Frases-padrão compartilhadas dos textos de O.S (conteúdo do app legado).
 * Portadas 1:1 do bundle (qD, QD, $D, eO, nO, tO).
 */

/** Separador de blocos. (legado: qD) */
export const SEP = '*';

/** (legado: QD) */
export const OPCOES_INTRO =
  'DISPONIBILIZEI AO CLIENTE 2 OPÇÕES PARA PROSSEGUIR COM O UPGRADE:';

/** (legado: $D) */
export const OPCAO_VISITA_PAGA =
  '1° - AGENDAR UMA VISITA PRESENCIAL PARA REALIZAR TESTES, INSTRUÇÕES DO USO DE INTERNET, INFORMAÇÕES SOBRE COBERTURA WI-FI, REDE ELÉTRICA ETC; VISITA ESTA COM O CUSTO DE R$50,00 REFERENTE AO DESLOCAMENTO TÉCNICO A SER PAGO NO ATO EM DINHEIRO, CARTÃO OU PIX.';

/** (legado: eO) */
export const OPCAO_REMOTA =
  '2° - REALIZAR A ALTERAÇÃO DE PLANO REMOTAMENTE (DENTRO DO PRAZO DE ATÉ 72 HORAS) E APÓS CONCLUÍDO A ALTERAÇÃO O CLIENTE REALIZAR A ASSINATURA DO CONTRATO DIGITAL POR MEIO DO APP "WBR" OU ATÉ MESMO COMPARECER DIRETAMENTE NA EMPRESA E REALIZAR ESTA ASSINATURA PRESENCIAL.';

/** (legado: nO) */
export const BENEFICIOS_APOS_ASSINATURA =
  'CIENTE QUE OS BENEFÍCIOS SÃO LIBERADOS APÓS ASSINATURA DO CONTRATO.';

/** (legado: tO) */
export const SEM_CUSTOS = 'PROCEDIMENTO ESTE QUE NÃO GERA CUSTOS AO ASSINANTE.';
