/**
 * Emulação do modelo `manut-sinal-alto` — porte 1:1 da função construtora `FWe`
 * do bundle legado (conteúdo de O.S do próprio app). Ramifica nos 5 tipos de
 * solicitação (titular/terceiro/PJ × acompanhamento). Retorna Protocolo, O.S e
 * o texto de agendamento da visita técnica. Validado por diff contra o legado —
 * ver `manutSinalAlto.diff.test.ts`.
 *
 * O 2º argumento do builder legado (`t`) era o `operadorPrimeiroNome`; aqui ele
 * é lido de `valores.operadorPrimeiroNome`.
 *
 * Mapeamento das variáveis do bundle (mantidas verbatim para fidelidade da
 * transcrição): i=cliente(maiúsc), a=1º nome cliente, o=solicitante(maiúsc),
 * s=1º nome solicitante, c=parente, l=cargo, u=canal, d=contato(dígitos),
 * f=contatoSol(dígitos), p=onu(maiúsc), m=1º "nome" da onu, h=sinal atual,
 * g=sinal anterior, _=oscilação, v=bairro, y=formaPag, b=dataVisita,
 * x=horaVisita, S=protocolo(maiúsc), C=ctoType, w=bloco CTO, t=operador.
 */
import { fraseFormaPag, maiusc, primeiroNome, soDigitos, type Valores } from './helpers';
import type { SaidaOS } from './altplanRemoto';

/** Separador do Protocolo — 19 asteriscos. (legado: xA) */
const SEP = '*'.repeat(19);
/** Separador da O.S antes da indicação técnica — 39 iguais. (legado: kWe) */
const SEP_EQ = '='.repeat(39);
/** Indicação técnica fixa da O.S. (legado: jWe) */
const INDICACAO_TECNICA =
  'TECNICO: VERIFICAR CONECTOR E DROP INTERNO E EXTERNO, ACHANDO O PROBLEMA APRESENTAR AO CLIENTE. SENDO DEFEITO EM QUE E DE OBRIGACAO DO PROVEDOR, TOMAR PROVIDENCIAS E RESTITUIR SEM CUSTO. SENDO OCASIONADO PEDIR AUTORIZACAO DO CLIENTE PARA CORRIGIR E RESTABELECER LEMBRANDO DO VALOR A SER COBRADO NO ATO. APOS RESTITUIR INTERNET, DAR EXPLICACOES SOBRE PLANO, WI-FI E DISPOSITIVOS, CORRIGIR QUALQUER INCONSISTENCIAS NA INSTALACAO QUE NAO TIVER PADRAO, ATUALIZAR FIRMWARE DO ROTEADOR SE ESTIVER DESATUALIZADA. TEMPO ESTIMADO 60 MIN.';

/** N espaços. (legado: OA) */
function espacos(n: number): string {
  return ' '.repeat(n);
}

/** Bloco CTO da O.S. (legado: NWe) */
function blocoCto(ctoType: string, cto: string, passante: string): string {
  if (ctoType === 'CTOE') return `\nCTOE: ${cto} // ${passante}.\n`;
  if (ctoType === 'CTOI') return `\nCTOI // ${passante}.\n`;
  return '';
}

/** Rodapé da O.S: separador + indicação técnica. (legado: PWe) */
function rodapeOS(): string {
  return `${SEP_EQ}\n\nINDICACAO TECNICA:\n\n${INDICACAO_TECNICA}`;
}

export function renderManutSinalAlto(valores: Valores): SaidaOS {
  const n: Valores = {};
  for (const [k, val] of Object.entries(valores)) n[k] = String(val ?? '');

  const r = n.tipoSolicitacao || 'titular-solicita-titular-acompanha';
  const i = maiusc(n.cliente);
  const a = primeiroNome(i);
  const o = maiusc(n.solicitante);
  const s = primeiroNome(o);
  const c = maiusc(n.parente);
  const l = maiusc(n.cargo);
  const u = n.canal ?? '';
  const d = soDigitos(n.contato);
  const f = soDigitos(n.contatoSol);
  const p = maiusc(n.onu);
  const m = primeiroNome(p);
  const h = maiusc(n.sinalONU);
  const g = maiusc(n.sinalONUan);
  const _ = maiusc(n.oscila);
  const v = maiusc(n.bairro);
  const y = n.formaPag ?? '';
  const b = n.dataVisita ?? '';
  const x = n.horaVisita ?? '';
  const S = maiusc(n.protocolo);
  const C = n.ctoType || 'CTOE';
  const w = blocoCto(C, maiusc(n.cto), maiusc(n.passante));
  const t = n.operadorPrimeiroNome ?? '';

  const OA = espacos;

  let T = `MAN SINAL ALTO ${i} PROT:${S} ${y} (${t}) - ${v}`;
  if (C === 'CTOI') T += ` *CTOI*`;

  let E = '';
  let D = '';

  if (r === 'pessoa-juridica') {
    E = [
      `${s} (${l}) ENTROU EM CONTATO POR ${u} (${f}) INFORMANDO PROBLEMA DE CONEXAO.`,
      ``,
      SEP,
      OA(4),
      `CLIENTE SEM BLOQUEIO, SEM REDUCAO E ${m} COM SINAL ${h} ${_}.`,
      OA(4),
      SEP,
      OA(4),
      `QUESTIONADO ${s} DISSE QUE ESTA SOFRENDO DESCONEXOES REPETIDAS EM SUA REDE, ALEGA QUE OS DISPOSITIVOS ESTAO CONECTADOS COM MENSAGEM DE CONECTADO SEM INTERNET OU APRESENTAM EXTREMA LENTIDAO. `,
      OA(4),
      `VERIFIQUEI REMOTAMENTE QUE A ${m} ESTA COM SINAL ALTO FORA DO PADRAO. REGISTRO DE ULTIMA MANUTENCAO ERA ${g}, SINAL ATUAL ${h} ${_}. `,
      OA(4),
      SEP,
      OA(4),
      `ORIENTEI ${s} A DESCONECTAR EQUIPAMENTOS (${p}) DA REDE ELETRICA E RECONECTA-LOS APOS 30 SEGUNDOS. FEZ, POREM CONEXAO NAO RESTABELECEU. `,
      OA(4),
      `PERGUNTEI A ${s} SE EFETUOU ALGUMA MODIFICACAO/INTERVENCAO NA INSTALACAO E CLIENTE DISSE QUE NAO. `,
      OA(4),
      SEP,
      OA(4),
      `INFORMEI QUE E NECESSARIO VISITA TECNICA PARA VERIFICAR A FONTE DO PROBLEMA E QUE HAVENDO PROBLEMA DA RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTOS, MAS, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO), SERA COBRADA VISITA TECNICA DE R$50,00 E CASO OS EQUIPAMENTOS TENHAM DEFEITOS OCASIONADOS, SERA COBRADO O VALOR REFERENTE AOS MESMOS.`,
      OA(4),
      SEP,
      OA(4),
      `${s} CONCORDOU COM OS TERMOS DA VISITA TECNICA E CASO HAJA CUSTOS PAGARA ${fraseFormaPag(y)}, DISSE QUE ESTARA PRESENTE PARA ACOMPANHAR O TECNICO. VISITA AGENDADA PARA O DIA ${b} AS ${x} HRS.`,
      ``,
      `CLIENTE SEM DUVIDAS.`,
    ].join('\n');
    D = `${s} (${l}) ENTROU EM CONTATO VIA ${u} (${f}) E DISSE QUE ESTA COM DESCONEXOES REPETIDAS, QUESTIONADO(A) DISSE QUE "TODOS APARELHOS DE SUA RESIDENCIA PERDEM CONEXAO COM A INTERNET REPETIDAS VEZES DURANTE O DIA (FICA CONECTADO AO WIFI E SEM INTERNET)". REMOTAMENTE VERIFIQUEI QUE CONSTAM VARIAS DESCONEXOES, ONU ACESA COM SINAL ALTO FORA DO PADRAO (${h} ${_}), FOI INSTALADO COM ${g}. ORIENTEI CLIENTE A DESCONECTAR AS FONTES DE ENERGIA DOS EQUIPAMENTOS (${p}) E RECONECTA-LOS APOS 30 SEGUNDOS, FEITO POREM CONEXAO E SINAL NAO NORMALIZOU. PERGUNTEI A ${s} SE EFETUOU ALGUMA MODIFICACAO/INTERVENCAO NA INSTALACAO E CLIENTE DISSE QUE NAO. INFORMEI A ${s} QUE E NECESSARIO VISITA TECNICA, QUE HAVENDO PROBLEMAS DA RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTO, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO) COBRA-SE VISITA TECNICA DE R$50,00 E ATE MESMO EQUIPAMENTOS DANIFICADOS. ${s} DISSE ESTA CIENTE E CONCORDOU COM A VISITA E CASO HAJA COBRANCA SERA PAGO NO ATO COM ${y}. VISITA AGENDADA PARA DIA ${b} AS ${x} HRS.`;
  } else if (r === 'terceiro-solicita-terceiro-acompanha') {
    E = [
      `${s} (${c} DE ${a}) ENTROU EM CONTATO POR ${u} (${f}) INFORMANDO PROBLEMA DE CONEXAO.`,
      ``,
      SEP,
      OA(4),
      `CLIENTE SEM BLOQUEIO, SEM REDUCAO E ${m} COM SINAL ${h} ${_}.`,
      OA(4),
      SEP,
      OA(4),
      `QUESTIONADO ${s} DISSE QUE ESTA SOFRENDO DESCONEXOES REPETIDAS EM SUA REDE, ALEGA QUE OS DISPOSITIVOS ESTAO CONECTADOS COM MENSAGEM DE CONECTADO SEM INTERNET OU APRESENTAM EXTREMA LENTIDAO. `,
      OA(4),
      `VERIFIQUEI REMOTAMENTE QUE A ${m} ESTA COM SINAL ALTO FORA DO PADRAO. REGISTRO DE ULTIMA MANUTENCAO ERA ${g}, SINAL ATUAL ${h} ${_}. `,
      OA(4),
      SEP,
      OA(4),
      `ORIENTEI ${s} A DESCONECTAR EQUIPAMENTOS (${p}) DA REDE ELETRICA E RECONECTA-LOS APOS 30 SEGUNDOS. FEZ, POREM CONEXAO NAO RESTABELECEU. `,
      OA(4),
      `PERGUNTEI A ${s} SE EFETUOU ALGUMA MODIFICACAO/INTERVENCAO NA INSTALACAO E CLIENTE DISSE QUE NAO.`,
      ``,
      SEP,
      OA(4),
      `INFORMEI QUE E NECESSARIO VISITA TECNICA PARA VERIFICAR A FONTE DO PROBLEMA E QUE HAVENDO PROBLEMA DA RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTOS, MAS, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO), SERA COBRADA VISITA TECNICA DE R$50,00 E CASO OS EQUIPAMENTOS TENHAM DEFEITOS OCASIONADOS, SERA COBRADO O VALOR REFERENTE AOS MESMOS.`,
      OA(4),
      SEP,
      OA(4),
      `POR PROCEDIMENTO PADRAO ENTREI EM CONTATO POR ${u} (${d}) COM ${a} (ASSINANTE) QUE CONFIRMOU E AUTORIZOU ${o} (${c}) ACOMPANHAR, ASSINAR O.S E EFETUAR O PAGAMENTO CASO HOUVER. ${a} CONCORDOU COM OS TERMOS DA VISITA TECNICA E CASO HAJA CUSTOS PAGARA ${fraseFormaPag(y)}. VISITA AGENDADA PARA O DIA ${b} AS ${x} HRS.`,
      ``,
      `CLIENTE SEM DUVIDAS.`,
    ].join('\n');
    D = `${s} (${c} DE ${a}) ENTROU EM CONTATO POR ${u} (${f}) E DISSE QUE ESTA COM DESCONEXOES REPETIDAS, QUESTIONADO(A) DISSE QUE "TODOS APARELHOS DE SUA RESIDENCIA PERDEM CONEXAO COM A INTERNET REPETIDAS VEZES DURANTE O DIA (FICA CONECTADO AO WIFI E SEM INTERNET)". REMOTAMENTE VERIFIQUEI QUE CONSTAM VARIAS DESCONEXOES, ONU ACESA COM SINAL ALTO FORA DO PADRAO (${h} ${_}), FOI INSTALADO COM ${g}. ORIENTEI CLIENTE A DESCONECTAR AS FONTES DE ENERGIA DOS EQUIPAMENTOS (${p}) E RECONECTA-LOS APOS 30 SEGUNDOS, FEITO POREM CONEXAO E SINAL NAO NORMALIZOU. PERGUNTEI A ${s} SE EFETUOU ALGUMA MODIFICACAO/INTERVENCAO NA INSTALACAO E CLIENTE DISSE QUE NAO. INFORMEI A ${s} QUE E NECESSARIO VISITA TECNICA, QUE HAVENDO PROBLEMAS DA RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTO, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO) COBRA-SE VISITA TECNICA DE R$50,00 E ATE MESMO EQUIPAMENTOS DANIFICADOS. ${s} DISSE ESTA CIENTE E CONCORDOU COM A VISITA E CASO HAJA COBRANCA SERA PAGO NO ATO COM ${y}. POR PROCEDIMENTO PADRAO ENTREI EM CONTATO POR ${u} (${d}) COM ${a} (ASSINANTE) QUE CONFIRMOU E AUTORIZOU ${o} (${c}) ACOMPANHAR, ASSINAR O.S E EFETUAR O PAGAMENTO CASO HOUVER. VISITA AGENDADA (A PEDIDO DO CLIENTE) PARA ${b} AS ${x} HRS.`;
  } else if (r === 'terceiro-solicita-titular-acompanha') {
    E = [
      `${s} (${c} DE ${a}) ENTROU EM CONTATO POR ${u} (${f}) INFORMANDO PROBLEMA DE CONEXAO.`,
      ``,
      SEP,
      OA(4),
      `CLIENTE SEM BLOQUEIO, SEM REDUCAO E ${m} COM SINAL ${h} ${_}.`,
      ``,
      SEP,
      OA(4),
      `QUESTIONADO ${s} DISSE QUE ESTA SOFRENDO DESCONEXOES REPETIDAS EM SUA REDE, ALEGA QUE OS DISPOSITIVOS ESTAO CONECTADOS COM MENSAGEM DE CONECTADO SEM INTERNET OU APRESENTAM EXTREMA LENTIDAO. `,
      OA(4),
      `VERIFIQUEI REMOTAMENTE QUE A ${m} ESTA COM SINAL ALTO FORA DO PADRAO. REGISTRO DE ULTIMA MANUTENCAO ERA ${g}, SINAL ATUAL ${h} ${_}. `,
      OA(4),
      SEP,
      OA(4),
      `ORIENTEI ${s} A DESCONECTAR EQUIPAMENTOS (${p}) DA REDE ELETRICA E RECONECTA-LOS APOS 30 SEGUNDOS. FEZ, POREM CONEXAO NAO RESTABELECEU. `,
      OA(4),
      `PERGUNTEI A ${s} SE EFETUOU ALGUMA MODIFICACAO/INTERVENCAO NA INSTALACAO E CLIENTE DISSE QUE NAO. `,
      OA(4),
      SEP,
      OA(4),
      `INFORMEI QUE E NECESSARIO VISITA TECNICA PARA VERIFICAR A FONTE DO PROBLEMA E QUE HAVENDO PROBLEMA DA RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTOS, MAS, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO), SERA COBRADA VISITA TECNICA DE R$50,00 E CASO OS EQUIPAMENTOS TENHAM DEFEITOS OCASIONADOS, SERA COBRADO O VALOR REFERENTE AOS MESMOS.`,
      OA(4),
      SEP,
      OA(4),
      `POR PROCEDIMENTO PADRAO ENTREI EM CONTATO POR ${u} (${d}) COM ${a} (ASSINANTE) QUE CONFIRMOU E DISSE QUE ESTARA PRESENTE PARA ACOMPANHAR, ASSINAR O.S E EFETUAR O PAGAMENTO CASO HOUVER. VISITA AGENDADA (A PEDIDO DO CLIENTE) PARA ${b} AS ${x} HRS.`,
      ``,
      `CLIENTE SEM DUVIDAS.`,
    ].join('\n');
    D = `${s} (${c} DE ${a}) ENTROU EM CONTATO POR ${u} (${f}) E DISSE QUE ESTA COM DESCONEXOES REPETIDAS, QUESTIONADO(A) DISSE QUE "TODOS APARELHOS DE SUA RESIDENCIA PERDEM CONEXAO COM A INTERNET REPETIDAS VEZES DURANTE O DIA (FICA CONECTADO AO WIFI E SEM INTERNET)". REMOTAMENTE VERIFIQUEI QUE CONSTAM VARIAS DESCONEXOES, ONU ACESA COM SINAL ALTO FORA DO PADRAO (${h} ${_}), FOI INSTALADO COM ${g}. ORIENTEI CLIENTE A DESCONECTAR AS FONTES DE ENERGIA DOS EQUIPAMENTOS (${p}) E RECONECTA-LOS APOS 30 SEGUNDOS, FEITO POREM CONEXAO E SINAL NAO NORMALIZOU. PERGUNTEI A ${s} SE EFETUOU ALGUMA MODIFICACAO/INTERVENCAO NA INSTALACAO E CLIENTE DISSE QUE NAO. INFORMEI A ${s} QUE E NECESSARIO VISITA TECNICA, QUE HAVENDO PROBLEMAS DA RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTO, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO) COBRA-SE VISITA TECNICA DE R$50,00 E ATE MESMO EQUIPAMENTOS DANIFICADOS. ${s} DISSE ESTA CIENTE E CONCORDOU COM A VISITA E CASO HAJA COBRANCA SERA PAGO NO ATO COM ${y}. POR PROCEDIMENTO PADRAO ENTREI EM CONTATO POR ${u} (${d}) COM ${a} (ASSINANTE) QUE CONFIRMOU E DISSE QUE ESTARA PRESENTE PARA ACOMPANHAR, ASSINAR O.S E EFETUAR O PAGAMENTO CASO HOUVER. VISITA AGENDADA (A PEDIDO DO CLIENTE) PARA ${b} AS ${x} HRS.`;
  } else if (r === 'titular-solicita-terceiro-acompanha') {
    E = [
      `${a} ENTROU EM CONTATO POR ${u} (${d}) INFORMANDO PROBLEMA DE CONEXAO.`,
      ``,
      SEP,
      OA(4),
      `CLIENTE SEM BLOQUEIO, SEM REDUCAO E ${m} COM SINAL ${h} ${_}.`,
      OA(4),
      SEP,
      OA(4),
      `QUESTIONADO ${a} DISSE QUE ESTA SOFRENDO DESCONEXOES REPETIDAS EM SUA REDE, ALEGA QUE OS DISPOSITIVOS ESTAO CONECTADOS COM MENSAGEM DE CONECTADO SEM INTERNET OU APRESENTAM EXTREMA LENTIDAO. `,
      OA(4),
      `VERIFIQUEI REMOTAMENTE QUE A ${m} ESTA COM SINAL ALTO FORA DO PADRAO. REGISTRO DE ULTIMA MANUTENCAO ERA ${g}, SINAL ATUAL ${h} ${_}. `,
      OA(4),
      SEP,
      OA(4),
      `ORIENTEI ${a} A DESCONECTAR EQUIPAMENTOS (${p}) DA REDE ELETRICA E RECONECTA-LOS APOS 30 SEGUNDOS. FEZ, POREM CONEXAO NAO RESTABELECEU. `,
      OA(4),
      `PERGUNTEI A ${a} SE EFETUOU ALGUMA MODIFICACAO/INTERVENCAO NA INSTALACAO E CLIENTE DISSE QUE NAO. `,
      OA(4),
      SEP,
      OA(4),
      `INFORMEI QUE E NECESSARIO VISITA TECNICA PARA VERIFICAR A FONTE DO PROBLEMA E QUE HAVENDO PROBLEMA DA RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTOS, MAS, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO), SERA COBRADA VISITA TECNICA DE R$50,00 E CASO OS EQUIPAMENTOS TENHAM DEFEITOS OCASIONADOS, SERA COBRADO O VALOR REFERENTE AOS MESMOS.`,
      OA(4),
      SEP,
      OA(4),
      `${a} CONCORDOU COM A VISITA E CASO HAJA COBRANCA SOLICITOU PAGAR NO ATO ${fraseFormaPag(y)}. ${a} DISSE QUE NAO ESTARA PRESENTE, MAS AUTORIZOU ${o} (${c}) A ACOMPANHAR, ASSINAR O.S E EFETUAR O PAGAMENTO CASO HOUVER. VISITA AGENDADA (A PEDIDO DO CLIENTE) PARA ${b} AS ${x} HRS.`,
      ``,
      `CLIENTE SEM DUVIDAS.`,
    ].join('\n');
    D = `${a} ENTROU EM CONTATO VIA ${u} (${d}) E DISSE QUE ESTA COM DESCONEXOES REPETIDAS, QUESTIONADO(A) DISSE QUE "TODOS APARELHOS DE SUA RESIDENCIA PERDEM CONEXAO COM A INTERNET REPETIDAS VEZES DURANTE O DIA (FICA CONECTADO AO WIFI E SEM INTERNET)". REMOTAMENTE VERIFIQUEI QUE CONSTAM VARIAS DESCONEXOES, ONU ACESA COM SINAL ALTO FORA DO PADRAO (${h} ${_}), FOI INSTALADO COM ${g}. ORIENTEI CLIENTE A DESCONECTAR AS FONTES DE ENERGIA DOS EQUIPAMENTOS (${p}) E RECONECTA-LOS APOS 30 SEGUNDOS, FEITO POREM CONEXAO E SINAL NAO NORMALIZOU. PERGUNTEI A ${a} SE EFETUOU ALGUMA MODIFICACAO/INTERVENCAO NA INSTALACAO E CLIENTE DISSE QUE NAO. INFORMEI A ${a} QUE E NECESSARIO VISITA TECNICA, QUE HAVENDO PROBLEMAS DA RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTO, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO) COBRA-SE VISITA TECNICA DE R$50,00 E ATE MESMO EQUIPAMENTOS SE DANIFICADOS. ${a} DISSE ESTA CIENTE E CONCORDOU COM A VISITA E CASO HAJA COBRANCA SERA PAGO NO ATO COM ${y}. ${a} DISSE QUE NAO ESTARA PRESENTE, MAS AUTORIZOU ${o} (${c}) A ACOMPANHAR, ASSINAR O.S E EFETUAR O PAGAMENTO CASO HOUVER. VISITA AGENDADA (A PEDIDO DO CLIENTE) PARA ${b} AS ${x} HRS.`;
  } else {
    E = [
      `${a} ENTROU EM CONTATO POR ${u} (${d}) INFORMANDO PROBLEMA DE CONEXAO.`,
      ``,
      SEP,
      OA(4),
      `CLIENTE SEM BLOQUEIO, SEM REDUCAO E ${m} COM SINAL ${h} ${_}.`,
      OA(4),
      SEP,
      OA(4),
      `QUESTIONADO ${a} DISSE QUE ESTA SOFRENDO DESCONEXOES REPETIDAS EM SUA REDE, ALEGA QUE OS DISPOSITIVOS ESTAO CONECTADOS COM MENSAGEM DE CONECTADO SEM INTERNET OU APRESENTAM EXTREMA LENTIDAO. `,
      OA(4),
      `VERIFIQUEI REMOTAMENTE QUE A ${m} ESTA COM SINAL ALTO FORA DO PADRAO. REGISTRO DE ULTIMA MANUTENCAO ERA ${g}, SINAL ATUAL ${h} ${_}. `,
      OA(4),
      SEP,
      OA(4),
      `ORIENTEI ${a} A DESCONECTAR EQUIPAMENTOS (${p}) DA REDE ELETRICA E RECONECTA-LOS APOS 30 SEGUNDOS. FEZ, POREM CONEXAO NAO RESTABELECEU. `,
      OA(4),
      `PERGUNTEI A ${a} SE EFETUOU ALGUMA MODIFICACAO/INTERVENCAO NA INSTALACAO E CLIENTE DISSE QUE NAO. `,
      OA(4),
      SEP,
      OA(4),
      `INFORMEI QUE E NECESSARIO VISITA TECNICA PARA VERIFICAR A FONTE DO PROBLEMA E QUE HAVENDO PROBLEMA DA RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTOS, MAS, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO), SERA COBRADA VISITA TECNICA DE R$50,00 E CASO OS EQUIPAMENTOS TENHAM DEFEITOS OCASIONADOS, SERA COBRADO O VALOR REFERENTE AOS MESMOS.`,
      OA(4),
      SEP,
      OA(4),
      `${a} CONCORDOU COM OS TERMOS DA VISITA TECNICA E CASO HAJA CUSTOS PAGARA ${fraseFormaPag(y)}, DISSE QUE ESTARA PRESENTE PARA ACOMPANHAR O TECNICO. VISITA AGENDADA PARA O DIA ${b} AS ${x} HRS.`,
      ``,
      `CLIENTE SEM DUVIDAS.`,
    ].join('\n');
    D = `${a} ENTROU EM CONTATO VIA ${u} (${d}) E DISSE QUE ESTA COM DESCONEXOES REPETIDAS, QUESTIONADO(A) DISSE QUE "TODOS APARELHOS DE SUA RESIDENCIA PERDEM CONEXAO COM A INTERNET REPETIDAS VEZES DURANTE O DIA (FICA CONECTADO AO WIFI E SEM INTERNET)". REMOTAMENTE VERIFIQUEI QUE CONSTAM VARIAS DESCONEXOES, ONU ACESA COM SINAL ALTO FORA DO PADRAO (${h} ${_}), FOI INSTALADO COM ${g}. ORIENTEI CLIENTE A DESCONECTAR AS FONTES DE ENERGIA DOS EQUIPAMENTOS (${p}) E RECONECTA-LOS APOS 30 SEGUNDOS, FEITO POREM CONEXAO E SINAL NAO NORMALIZOU. PERGUNTEI A ${a} SE EFETUOU ALGUMA MODIFICACAO/INTERVENCAO NA INSTALACAO E CLIENTE DISSE QUE NAO. INFORMEI A ${a} QUE E NECESSARIO VISITA TECNICA, QUE HAVENDO PROBLEMAS DA RESPONSABILIDADE DO PROVEDOR VISITA NAO TERA CUSTO, SENDO PROBLEMA OCASIONADO (ESPONTANEO OU NAO) COBRA-SE VISITA TECNICA DE R$50,00 E ATE MESMO EQUIPAMENTOS DANIFICADOS. ${a} DISSE ESTA CIENTE E CONCORDOU COM A VISITA E CASO HAJA COBRANCA SERA PAGO NO ATO COM ${y}. VISITA AGENDADA PARA DIA ${b} AS ${x} HRS.`;
  }

  const O = D + w + rodapeOS();
  return { protocolo: E, os: O, agenda: T };
}
